### PR TITLE
Initial scripting support for multi-fpga configuration

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-engine-simulation-toolkit-custom-device/blob/master/CONTRIBUTING.md).

## What is this pull request/scripting API?

- A way to generate/modify an EST custom device programmatically, knowing the intended configuration 
  - Supports adding and removing, getting and setting the configuration for the custom device, APUs, and Analog Replays
  - Supports adding and removing bitfiles by RIO address, and getting and setting the master RIO device
    - This part of the API is designed slightly differently since there is not one "RIO" or "bitfile" section in the custom device tree to refer to
- Purely additive
  - Other than changes to the `.lvproj` file itself, no existing files have been modified, which should make merging this in the presence of other pull requests easier

## What isn't this pull request/scripting API?

- A method for exploring an EST custom device to learn about its contents
  - Several missing pieces are needed to truly support this use case, including the ability to enumerate bitfiles/RIO devices, APUs, and analog replays
- Scripting support from built apps e.g. TestStand
  - This will come later, as the changes needed are potentially more invasive/widespread in terms of the VIs affected
- Fast
  - The VeriStand custom device API is relatively slow when called from LabVIEW due to manually opening VIs from disk
  - The speed should improve as part of the work to support calling from TestStand
- Fault tolerant
  - Very little is done to validate inputs to the API
  - Invalid requests currently may report success, or leave the user in an intermediate state with no clear option for recovery
- Duplication free
  - As part of making the pull request easy to merge asynchronously, the changes are purely additive. This required some duplication
  - We need to decide how the system explorer and scripting API should interact: with this implementation, the scripting API calls into the system explorer to re-use some of the existing logic. It might make sense to pull that common logic out into a separate lvlib, or to invert the dependency and have the system explorer call the scripting API.

## What testing has been done?

Tests have been added which exercise all of the API entrypoints. They have been written in a way that hopefully makes API usage clear. I recommend looking at `test Get Set Analog Replay.vi` to understand how a user might go about scripting an analog replay from scratch.

Due to the constantly changing nature of multi-fpga support in the custom device at the present, each test starts with an empty system definition, meaning some extra dependencies exist in the tests that could potentially be removed in the future. For example, if `Add Engine Simulation Toolkit Custom Device.vi` fails, all tests will fail as they depend on having a custom device.

### CODE REVIEW

**Comment by rtzoeller** [comment]
For some reason text in the VIs is being rendered larger than it should be in the images posted by the diff bot: https://github.com/ni/niveristand-custom-device-build-tools/issues/15

**Comment by csjall** [comment]
Scripting API Test Case.lvclass
- [ ] Remove 'None' property. Update setUp. vi and tearDown.vi accordingly.
- [ ] All the scripting tests currently have the same setup and teardown procedure. Consider moving to setUp.vi and tearDown.vi to cut back on unnecessary code duplication. If there is a compelling reason not to do this, then create private helper methods for common code.
image

Scripting Engine Simulation Scripting API.lvlib
- [ ] Why do we convert to/from the Analog Replay Data Options? Is this merely scrubbing other unneeded properties from the cluster or is there another reason to do this?
image
- [ ] Set Analog Replay Settings touch refer to the DataReplayVoltage. I don't see a corresponding access in the Get Analog Replay Settings Method.
image

**Comment by rtzoeller** [comment]
OOO so I won't be updating the pull request, but the primary reason for doing the Analog Replay Data Options dance is to strip and not expose implementation details in the public API.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rtzoeller** [comment]
> Set Analog Replay Settings touch refer to the DataReplayVoltage. I don't see a corresponding access in the Get Analog Replay Settings Method.

@csjall This is intentional. The existence of the channels specified by `ChanList.DataReplayVoltage` is dependent on `DataReplay.VOverride`; whenever `DataReplay.VOverride` is updated, we need to add or remove these channels. They are channels used at runtime, and not directly get/set during system definition scripting.

**Pull request merged**
